name: Jira → CodeX Generate Tests

on:
  repository_dispatch:
    types: [codex_generate_tests]
  workflow_dispatch:
    inputs:
      jira_key:
        description: "Jira issue key (e.g., ABC-123)"
        required: true
      mode:
        description: "repo | jira | both"
        required: false
        default: "repo"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      JIRA_BASE: ${{ secrets.JIRA_BASE }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
      CODEX_BASE: ${{ secrets.CODEX_BASE }}
      CODEX_API_KEY: ${{ secrets.CODEX_API_KEY }}
      AC_FIELD: customfield_12345          # <— replace with your AC field id
      TEST_ISSUETYPE_NAME: Test
      LINK_TYPE_NAME: Tests
    steps:
      - uses: actions/checkout@v4

      - name: Resolve inputs
        id: meta
        run: |
          if [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "JIRA_KEY=${{ github.event.client_payload.jira_key }}" >> $GITHUB_OUTPUT
            echo "MODE=${{ github.event.client_payload.mode || 'repo' }}" >> $GITHUB_OUTPUT
          else
            echo "JIRA_KEY=${{ github.event.inputs.jira_key }}" >> $GITHUB_OUTPUT
            echo "MODE=${{ github.event.inputs.mode }}" >> $GITHUB_OUTPUT
          fi

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests pyyaml

      - name: Generate tests (via CodeX, fallback local)
        run: |
          python .github/scripts/codex_jira_test_gen.py \
            --jira-key "${{ steps.meta.outputs.JIRA_KEY }}" \
            --mode "${{ steps.meta.outputs.MODE }}"

      - name: Create branch & PR (repo or both)
        if: steps.meta.outputs.MODE == 'repo' || steps.meta.outputs.MODE == 'both'
        run: |
          BR="tests/${{ steps.meta.outputs.JIRA_KEY }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BR"
          git add tests/generated/
          git commit -m "chore(tests): autogen for ${{ steps.meta.outputs.JIRA_KEY }}"
          git push origin "$BR" || true
          gh api repos/${{ github.repository }}/pulls -X POST -f title="Auto tests for ${{ steps.meta.outputs.JIRA_KEY }}" -f head="$BR" -f base="main" -f body="Generated by CodeX."
        env:
          GH_TOKEN: ${{ github.token }}
 
